import { useCallback, useEffect, useId, useRef, useState } from "react";
import { Link, NavLink, useNavigate } from "react-router-dom";
import { Search, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { cn } from "@/lib/utils";
import { MobileMenu } from "./MobileMenu";

const navItems = [{ to: "/", label: "Home", end: true }, { to: "/papers", label: "Papers" }, { to: "/categories", label: "Categories" }];
const FOCUSABLE_SELECTOR = 'a[href], button:not([disabled]), input:not([disabled]):not([type="hidden"]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';
function getFocusable(root: HTMLElement | null): HTMLElement[] { if (!root) return []; return Array.from(root.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)).filter((el) => !el.hasAttribute("aria-hidden")); }
function focusFirstInPanel(panel: HTMLElement | null, fallback: HTMLElement | null) { if (typeof document === "undefined") return; const target = getFocusable(panel)[0] ?? fallback; target?.focus?.({ preventScroll: true }); }

export function Header() {
  const navigate = useNavigate(); const [scrolled, setScrolled] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState("");
  const mobileCloseRef = useRef<HTMLButtonElement>(null); const mobilePanelRef = useRef<HTMLDivElement>(null); const mobileTriggerRef = useRef<HTMLButtonElement>(null); const searchInputRef = useRef<HTMLInputElement>(null); const searchPanelRef = useRef<HTMLDivElement>(null); const searchTriggerRef = useRef<HTMLButtonElement>(null); const mobileTitleId = useId(); const searchTitleId = useId();
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 8); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const dialogOpen = mobileOpen || searchOpen; if (!dialogOpen) return; const activeBeforeOpen = document.activeElement; const restoreTarget = activeBeforeOpen instanceof HTMLElement && (activeBeforeOpen === mobileTriggerRef.current || activeBeforeOpen === searchTriggerRef.current || activeBeforeOpen.closest("header")) ? activeBeforeOpen : null; const originalOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; requestAnimationFrame(() => mobileOpen ? focusFirstInPanel(mobilePanelRef.current, mobileCloseRef.current) : focusFirstInPanel(searchPanelRef.current, searchInputRef.current)); const onKeyDown = (e: KeyboardEvent) => { if (e.key === "Escape") { e.preventDefault(); searchOpen ? setSearchOpen(false) : setMobileOpen(false); return; } if (e.key !== "Tab") return; const panel = searchOpen ? searchPanelRef.current : mobilePanelRef.current; const focusables = getFocusable(panel); if (!focusables.length) { e.preventDefault(); return; } const first = focusables[0]; const last = focusables[focusables.length - 1]; const current = document.activeElement; if (!(current instanceof HTMLElement && panel?.contains(current))) { e.preventDefault(); first.focus(); } else if (e.shiftKey && current === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && current === last) { e.preventDefault(); first.focus(); } }; document.addEventListener("keydown", onKeyDown); return () => { document.body.style.overflow = originalOverflow; document.removeEventListener("keydown", onKeyDown); if (restoreTarget && document.contains(restoreTarget)) requestAnimationFrame(() => restoreTarget.focus({ preventScroll: true })); }; }, [mobileOpen, searchOpen]);
  const onSearchSubmit = (e: React.FormEvent) => { e.preventDefault(); const value = query.trim(); if (!value) { searchInputRef.current?.focus(); return; } setSearchOpen(false); setMobileOpen(false); navigate(`/search?q=${encodeURIComponent(value)}`); };
  const closeMobile = useCallback(() => setMobileOpen(false), []); const closeSearch = useCallback(() => setSearchOpen(false), []);
  return <>
    <header className={cn("site-header sticky top-0 z-40 w-full transition-all duration-200", scrolled ? "border-b border-border bg-bg/80 backdrop-blur-md" : "border-b border-transparent bg-bg")}>
      <div className="container flex h-16 items-center gap-6"><Link to="/" className="flex items-center gap-2 font-display text-lg font-semibold tracking-tight" aria-label="Micromath — Home"><Logo /><span>Micromath</span></Link><nav className="hidden items-center gap-1 md:flex" aria-label="Primary navigation">{navItems.map((item) => <NavLink key={item.to} to={item.to} end={item.end} className={({ isActive }) => cn("rounded-md px-3 py-1.5 text-sm font-medium transition-colors", isActive ? "text-fg" : "text-fg-muted hover:bg-bg-muted hover:text-fg")}>{item.label}</NavLink>)}</nav><div className="ml-auto flex items-center gap-2"><form onSubmit={onSearchSubmit} className="hidden md:block" role="search"><Input type="search" placeholder="Search papers…" value={query} onChange={(e) => setQuery(e.target.value)} leftIcon={<Search className="h-4 w-4" />} className="w-64" aria-label="Search papers" /></form><Button ref={searchTriggerRef} variant="ghost" size="md" className="md:hidden" onClick={() => { setMobileOpen(false); setSearchOpen(true); }} aria-label="Open search" aria-expanded={searchOpen} aria-controls="mobile-search"><Search className="h-4 w-4" /></Button><Button ref={mobileTriggerRef} variant="ghost" size="md" className="md:hidden" onClick={() => { setSearchOpen(false); setMobileOpen(true); }} aria-label="Open menu" aria-expanded={mobileOpen} aria-controls="mobile-navigation"><Menu className="h-4 w-4" /></Button></div></div>
    </header>
    {mobileOpen && <div id="mobile-navigation" className="fixed inset-0 z-50 animate-fade-in-fast md:hidden" role="dialog" aria-modal="true" aria-labelledby={mobileTitleId}><div className="absolute inset-0 bg-black/40" onClick={closeMobile} aria-hidden="true" /><div ref={mobilePanelRef} className="absolute right-0 top-0 flex h-full w-full max-w-sm animate-slide-in-right flex-col border-l border-border bg-bg"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 id={mobileTitleId} className="font-display text-lg font-semibold">Menu</h2><button ref={mobileCloseRef} type="button" onClick={closeMobile} className="inline-flex h-8 w-8 items-center justify-center rounded-md text-fg-muted hover:bg-bg-muted" aria-label="Close menu"><X className="h-4 w-4" /></button></div><MobileMenu onClose={closeMobile} /></div></div>}
    {searchOpen && <div id="mobile-search" className="fixed inset-0 z-50 animate-fade-in-fast md:hidden" role="dialog" aria-modal="true" aria-labelledby={searchTitleId}><div className="absolute inset-0 bg-black/40" onClick={closeSearch} aria-hidden="true" /><div ref={searchPanelRef} className="absolute left-0 right-0 top-0 border-b border-border bg-bg p-4"><h2 id={searchTitleId} className="sr-only">Search papers</h2><form onSubmit={onSearchSubmit} role="search"><Input ref={searchInputRef} type="search" placeholder="Search papers…" value={query} onChange={(e) => setQuery(e.target.value)} leftIcon={<Search className="h-4 w-4" />} size="lg" aria-label="Search papers" /><div className="mt-2 flex items-center justify-between"><span className="text-xs text-fg-subtle">Press Enter to search</span><Button variant="ghost" size="sm" onClick={closeSearch}>Cancel</Button></div></form></div></div>}
  </>;
}
function Logo() { return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden><path d="M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10-6h6v12h-6V8Z" stroke="currentColor" strokeWidth="1.5" fill="none" /></svg>; }
