import { useState } from "react";
import { ParticleBackground } from "@/components/ui/ParticleBackground";
import { Link, useNavigate } from "react-router-dom";
import { Search, ArrowRight, FileText } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { SearchInput } from "@/components/search/SearchInput";
import { SearchSuggestions } from "@/components/search/SearchSuggestions";
import { FeaturedPaperCard } from "@/components/papers/FeaturedPaperCard";
import { PaperCard } from "@/components/papers/PaperCard";
import { CategoryCard } from "@/components/categories/CategoryCard";
import { useFeaturedPapersQuery, useLatestPapersQuery } from "@/api/papers";
import { useCategoriesQuery } from "@/api/categories";
import { PaperCardSkeleton, Skeleton } from "@/components/ui/Skeleton";
import { Helmet } from "react-helmet-async";
import { ErrorState } from "@/components/feedback/ErrorState";
import { publicErrorMessage } from "@/api/client";

export function HomePage() {
  const navigate = useNavigate(); const [query, setQuery] = useState("");
  const { data: featured, isLoading: featuredLoading, isError: featuredError, error: featuredErrorValue, refetch: refetchFeatured } = useFeaturedPapersQuery();
  const { data: latest, isLoading: latestLoading, isError: latestError, error: latestErrorValue, refetch: refetchLatest } = useLatestPapersQuery(6);
  const { data: categories, isLoading: categoriesLoading, isError: categoriesError, error: categoriesErrorValue, refetch: refetchCategories } = useCategoriesQuery();
  const onSearch = (e: React.FormEvent) => { e.preventDefault(); if (query.trim()) navigate(`/search?q=${encodeURIComponent(query.trim())}`); };
  const onSuggestionSelect = (s: string) => navigate(`/search?q=${encodeURIComponent(s)}`);
  return <>
    <Helmet><title>Micromath — Understand the research that shapes tomorrow</title><meta name="description" content="Clear, structured explanations of important research papers — without requiring you to decode every page of the original paper." /></Helmet>
    <section className="micromath-home-hero relative overflow-hidden border-b border-border"><div className="hero-glyphs absolute inset-0 pointer-events-none z-[1] overflow-hidden" aria-hidden="true"><span className="absolute top-[15%] left-[8%] font-mono text-5xl text-fg-subtle/10 rotate-[-6deg]">∑</span><span className="absolute top-[30%] right-[10%] font-mono text-4xl text-fg-subtle/10 rotate-[4deg]">π</span><span className="absolute bottom-[20%] left-[12%] font-mono text-3xl text-fg-subtle/8 rotate-[3deg]">∫</span><span className="absolute top-[12%] right-[25%] font-mono text-2xl text-fg-subtle/10 rotate-[-3deg]">√</span><span className="absolute bottom-[30%] right-[8%] font-mono text-4xl text-fg-subtle/10 rotate-[6deg]">f(x)</span></div><ParticleBackground className="opacity-60" /><div className="relative z-10"><div className="container max-w-5xl py-20 md:py-28"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-bg-subtle px-3 py-1 text-xs text-fg-muted"><span className="h-1.5 w-1.5 rounded-full bg-success" aria-hidden />New explanations added weekly</div><h1 className="font-display text-4xl font-semibold leading-[1.05] tracking-tight text-fg md:text-6xl lg:text-7xl"><span className="text-balance">Understand the research that shapes tomorrow.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-fg-muted md:text-xl">Clear, structured explanations of important research papers — without requiring you to decode every page of the original paper.</p><form onSubmit={onSearch} className="mt-10 max-w-2xl" role="search"><div className="flex flex-col gap-3 sm:flex-row"><div className="flex-1"><SearchInput size="lg" type="search" placeholder="Search a paper, topic, or author…" value={query} onChange={(e) => setQuery(e.target.value)} onClear={() => setQuery("")} aria-label="Search papers" /></div><Button type="submit" size="lg" leftIcon={<Search className="h-4 w-4" />}>Search</Button></div><div className="mt-5"><SearchSuggestions onSelect={onSuggestionSelect} /></div></form></div></div></section>
    <section className="border-b border-border py-16 md:py-20"><div className="container"><div className="mb-10 flex items-end justify-between"><div><h2 className="font-display text-2xl font-semibold tracking-tight md:text-3xl">Featured research</h2><p className="mt-1.5 text-sm text-fg-muted">Hand-picked explanations of particularly important papers.</p></div><Link to="/papers" className="hidden items-center gap-1 text-sm font-medium text-fg-muted transition-colors hover:text-fg sm:inline-flex">View all papers<ArrowRight className="h-4 w-4" aria-hidden /></Link></div>{featuredLoading ? <div className="rounded-lg border border-border bg-bg p-8"><Skeleton /></div> : featuredError ? <ErrorState title="Could not load featured research" message={publicErrorMessage(featuredErrorValue)} onRetry={() => void refetchFeatured()} /> : featured?.length ? <FeaturedPaperCard paper={featured[0]} /> : null}</div></section>
    <section className="home-section-alt border-b border-border py-16 md:py-20"><div className="container"><div className="mb-10 flex items-end justify-between"><div><h2 className="font-display text-2xl font-semibold tracking-tight md:text-3xl">Latest explanations</h2><p className="mt-1.5 text-sm text-fg-muted">Recently published paper explanations.</p></div><Link to="/papers" className="hidden items-center gap-1 text-sm font-medium text-fg-muted transition-colors hover:text-fg sm:inline-flex">See more<ArrowRight className="h-4 w-4" aria-hidden /></Link></div>{latestLoading ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <PaperCardSkeleton key={i} />)}</div> : latestError ? <ErrorState title="Could not load latest papers" message={publicErrorMessage(latestErrorValue)} onRetry={() => void refetchLatest()} /> : latest?.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{latest.map((paper) => <PaperCard key={paper.id} paper={paper} />)}</div> : <div className="rounded-lg border border-border bg-bg-subtle p-12 text-center text-fg-muted"><FileText className="mx-auto mb-3 h-6 w-6" />No papers available yet.</div>}</div></section>
    <section className="border-b border-border bg-bg-subtle py-20 md:py-24"><div className="container"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-2xl font-semibold tracking-tight md:text-3xl">Why Micromath</h2><p className="mt-3 text-base text-fg-muted">Most research papers are written for specialists. We rewrite them for the rest of us — without losing the substance.</p></div><div className="mx-auto mt-12 max-w-3xl"><div className="flex flex-col items-stretch gap-3 md:flex-row md:items-center md:justify-between"><Step label="Original research" detail="Dense academic papers" /><ArrowRight className="hidden h-4 w-4 flex-shrink-0 text-fg-subtle md:block" /><Step label="Structured explanation" detail="Clear, sectioned, visual" highlight /><ArrowRight className="hidden h-4 w-4 flex-shrink-0 text-fg-subtle md:block" /><Step label="Understand faster" detail="In minutes, not hours" /></div></div></div></section>
    <section className="border-b border-border py-16 md:py-20"><div className="container"><div className="mb-10 flex items-end justify-between"><div><h2 className="font-display text-2xl font-semibold tracking-tight md:text-3xl">Browse by category</h2><p className="mt-1.5 text-sm text-fg-muted">Explore explanations organized by research area.</p></div><Link to="/categories" className="hidden items-center gap-1 text-sm font-medium text-fg-muted transition-colors hover:text-fg sm:inline-flex">All categories<ArrowRight className="h-4 w-4" aria-hidden /></Link></div>{categoriesLoading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <div key={i} className="h-32 rounded-lg border border-border bg-bg p-5"><Skeleton className="h-8 w-8 rounded-md" /><Skeleton className="mt-4 h-4 w-2/3" /></div>)}</div> : categoriesError ? <ErrorState title="Could not load categories" message={publicErrorMessage(categoriesErrorValue)} onRetry={() => void refetchCategories()} /> : categories?.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0, 8).map((category) => <CategoryCard key={category.id} category={category} />)}</div> : <div className="rounded-lg border border-border bg-bg-subtle p-12 text-center text-fg-muted">No categories available yet.</div>}</div></section>
  </>;
}
function Step({ label, detail, highlight }: { label: string; detail: string; highlight?: boolean }) { return <div className={`flex-1 rounded-lg border p-5 text-center ${highlight ? "border-fg bg-fg text-fg-inverse" : "border-border bg-bg"}`}><div className={`text-sm font-semibold ${highlight ? "text-fg-inverse" : "text-fg"}`}>{label}</div><div className={`mt-1 text-xs ${highlight ? "text-fg-inverse/70" : "text-fg-muted"}`}>{detail}</div></div>; }
